
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

public class produk extends javax.swing.JFrame implements ConnSpecs{

    public produk(){
        initComponents();
        setkat();
        tampil();
         
        try {
             BufferedImage beam = ImageIO.read(getClass().getResource("kebun.jpg"));
             setIconImage(beam); 
        } catch (IOException ex) {
            Logger.getLogger(splashscreen.class.getName()).log(Level.SEVERE, null, ex);
        }
       this.setTitle("Aplikasi Perpustakaan");
    }
    @Override
    public void setkat(){
    cmbkat.addItem("Sayur Sayuran");
    cmbkat.addItem("Buah Buahan");
    cmbkat.addItem("Produk Mentah");

}

private void tampil(){
    try{
        String id = session.getid();
        String query ="select*from produk where id_produk = '"+id+"'";
        Connection kon = (Connection) koneksi.koneksi();
        Statement stm = kon.createStatement();
        ResultSet data = stm.executeQuery(query);
        while(data.next()){
         lblid.setText(data.getString(1));
         txtjudul.setText(data.getString(2));
         txtpengarang.setText(data.getString(3));
         txtpenerbit.setText(data.getString(4));
         cmbkat.setSelectedItem(data.getString(5));
         txtdesc.setText(data.getString(6));
         txtstok.setText(data.getString(7));
        }
        
    }catch(Exception b){
        
    }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtpengarang = new javax.swing.JTextField();
        txtpenerbit = new javax.swing.JTextField();
        txtjudul = new javax.swing.JTextField();
        cmbkat = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdesc = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtstok = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        lblid = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtpengarang.setText("Petani");
        txtpengarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpengarangMouseClicked(evt);
            }
        });
        txtpengarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpengarangActionPerformed(evt);
            }
        });
        jPanel1.add(txtpengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 380, 42));

        txtpenerbit.setText("Tgl Panen");
        txtpenerbit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpenerbitMouseClicked(evt);
            }
        });
        jPanel1.add(txtpenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 380, 46));

        txtjudul.setText("Produk");
        txtjudul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtjudulMouseClicked(evt);
            }
        });
        txtjudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjudulActionPerformed(evt);
            }
        });
        jPanel1.add(txtjudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 380, 42));

        cmbkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkatActionPerformed(evt);
            }
        });
        jPanel1.add(cmbkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 95, -1));

        txtdesc.setColumns(20);
        txtdesc.setRows(5);
        txtdesc.setText("\n   Deskripsi Prosuk");
        txtdesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdescMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtdesc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 380, 50));

        jButton2.setBackground(new java.awt.Color(0, 255, 0));
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 87, 36));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 84, 36));

        txtstok.setText("Stok");
        txtstok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtstokMouseClicked(evt);
            }
        });
        txtstok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtstokKeyTyped(evt);
            }
        });
        jPanel1.add(txtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 65, 25));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 384, 110, 110));

        lblid.setText("jLabel1");
        lblid.setOpaque(true);
        jPanel1.add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel2.setText("Input Produk");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(237, 237, 237))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tea-plantation-wallpaper-preview.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtpengarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpengarangMouseClicked
        txtpengarang.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpengarangMouseClicked

    private void txtpenerbitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpenerbitMouseClicked
        txtpenerbit.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpenerbitMouseClicked

    private void txtjudulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtjudulMouseClicked
        txtjudul.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjudulMouseClicked

    private void txtdescMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdescMouseClicked
        txtdesc.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String kat = (String) cmbkat.getSelectedItem();
        String jdl = (String) txtjudul.getText();
        String penga = (String) txtpengarang.getText();
        String pener = (String) txtpenerbit.getText();
        String desc = (String) txtdesc.getText();
        String stk = (String) txtstok.getText();

        if(kat.equals("Kategori")){
            JOptionPane.showMessageDialog(null, "Pilih Kategori!");
        }
        else if(jdl.equals("")||penga.equals("")||pener.equals("")||desc.equals("")||stk.equals("")){
            JOptionPane.showMessageDialog(null, "Tidak Boleh Ada Yang Kosong!");
        }
        else{
             try {
            String query ="UPDATE produk SET id_produk = '"+lblid.getText()
                    +"',produk = '"+txtjudul.getText()
                    +"', petani = '"+txtpengarang.getText()
                    +"',tgl_panen = '"+txtpenerbit.getText()
                    +"',kategori = '"+cmbkat.getSelectedItem()
                    +"',deskripsi = '"+txtdesc.getText()
                    +"',stok = '"+txtstok.getText()
                    +"' WHERE id_produk = '"+lblid.getText()+"'";
            java.sql.Connection kon=(Connection)koneksi.koneksi();
            java.sql.PreparedStatement pdt=kon.prepareStatement(query);
            pdt.execute();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
             new beranda().setVisible(true);
dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtstokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtstokMouseClicked
        txtstok.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstokMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new beranda().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try {
            String sql ="delete from produk where id_produk='"+lblid.getText()+"'";
            java.sql.Connection conn=(Connection)koneksi.koneksi();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "berhasil di hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
new beranda().setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtstokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstokKeyTyped
char c = evt.getKeyChar();
        if (! ((Character.isDigit(c) ||
                (c == KeyEvent.VK_BACK_SPACE) ||
                (c == KeyEvent.VK_DELETE))
                )
            )
        {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtstokKeyTyped

    private void txtjudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjudulActionPerformed

    private void txtpengarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpengarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpengarangActionPerformed

    private void cmbkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbkatActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbkat;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblid;
    private javax.swing.JTextArea txtdesc;
    private javax.swing.JTextField txtjudul;
    private javax.swing.JTextField txtpenerbit;
    private javax.swing.JTextField txtpengarang;
    private javax.swing.JTextField txtstok;
    // End of variables declaration//GEN-END:variables
}
